### ISSUE TITLE
Weird  Behavior with simple test

### ISSUE THREAD

**Issue by mcg-web** [nexylan/gandi-sdk#9]
Hi, When playing this simple test 
`(new \Nexy\Gandi\Gandi('__MY_API_KEY__', 'https://rpc.ote.gandi.net/xmlrpc/'))->domain()->isAvailable(['www.test.com']);`

I got a bad http request:

```
PHP Fatal error:  Uncaught fXmlRpc\Exception\HttpException: An HTTP error occurred: Bad request in /projects/domain/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/HttpException.php:32
Stack trace:
#0 /projects/domain/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Transport/HttpAdapterTransport.php(58): fXmlRpc\Exception\HttpException::httpError('Bad request', 400)
#1 /projects/domain/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php(154): fXmlRpc\Transport\HttpAdapterTransport->send('https://rpc.ote...', '<?xml version="...')
#2 /projects/domain/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Proxy.php(61): fXmlRpc\Client->call('domain.availabl...', Array)
#3 /projects/domain/vendor/nexylan/gandi-sdk/src/Api/Domain.php(29): fXmlRpc\Proxy->__call('available', Array)
#4 /projects/domain/test.php(39): Nexy\Gandi\Ap in /projects/domain/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/HttpException.php on line 3
```

**Comment by mcg-web** [comment]
Ok I find out why, it's because documentation missing some information about dependencies https://github.com/lstrojny/fxmlrpc#install-dependencies . Please keep this open, I submit a PR later to complete documentation and composer suggestions, thank you.

**Comment by flubble** [comment]
Closed due to inactivity.
